# -*- coding: utf-8 -*-
"""05.04.01 Exercícios if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JjcqciIJtjIfCFgoiGJIHEAwsVXTME1Z

# Exercícios com if

## 1. Cálculo de Bônus

- Crie um programa que calcule e dê um print no bônus que os funcionários devem receber segundo a regra:

A meta é 1000 vendas.
Se o valor de vendas for maior ou igual a meta, o valor do bônus do funcionário é 10% do valor de vendas.
Caso contrário o valor de bônus do funcionário é 0.
Print o bônus dos 3 funcionários
"""

vendas_funcionario1 = 1000
vendas_funcionario2 = 770
vendas_funcionario3 = 2700
meta = 1000

if vendas_funcionario1 >= meta:
    bonus = vendas_funcionario1 * 0.10
    print("Funcionario 01 recebeu {} em bonus".format(bonus))
else:
    print("O funcionário 01 ganhou 0 bonus")

if vendas_funcionario2 >= meta:
    bonus = vendas_funcionario2 * 0.10
    print("Funcionario 02 recebeu {} em bonus".format(bonus))
else:
    print("O funcionário 02 ganhou 0 bonus")

if vendas_funcionario3 >= meta:
    bonus = vendas_funcionario3 * 0.10
    print("Funcionario 03 recebeu {} em bonus".format(bonus))
else:
    print("O funcionário 03 ganhou 0 bonus")

"""Resposta:
O funcionário 1 ganhou 100 de bônus
O funcionário 2 ganhou 0 de bônus
O funcionário 3 ganhou 270 de bônus

## 2. Cálculo de bônus com uma nova regra

- Agora, crie um novo código que calcule e dê um print no bônus dos funcionários novamente.
Porém há uma nova regra nesse 2º caso:

A meta é 1000 vendas
Agora, os funcionários que venderem muito acima da meta ganham mais bônus do que os outros.
Então o bônus é definido da seguinte forma:

- Se vendas funcionário for maior ou igual a 2000, então o bônus é de 15% sobre o valor de vendas
- Se vendas funcionário for menor do que 2000 e maior ou igual a 1000, então o bônus é de 10% sobre o valor de vendas
- Se vendas funcionário for menos do que 1000 então o bônus do funcionário é de 0.

Use as mesmas variáveis de vendas_funcionários
"""

if vendas_funcionario1 >= (meta * 2):
    bonus = vendas_funcionario1 * 0.15
    print("Funcionario 01 recebeu {} em bonus".format(bonus))
elif (vendas_funcionario1 < (meta * 2)) and (vendas_funcionario1 >= meta):
    bonus = vendas_funcionario1 * 0.10
    print("Funcionário 01 recebeu {} em bonus".format(bonus))
else:
    print("O funcionário 01 ganhou 0 bonus")

if vendas_funcionario2 >= (meta * 2):
    bonus = vendas_funcionario2 * 0.15
    print("Funcionario 02 recebeu {} em bonus".format(bonus))
elif (vendas_funcionario2 < (meta * 2)) and (vendas_funcionario2 >= meta):
    bonus = vendas_funcionario2 * 0.10
    print("Funcionário 02 recebeu {} em bonus".format(bonus))
else:
    print("O funcionário 02 ganhou 0 bonus")

if vendas_funcionario3 >= (meta * 2):
    bonus = vendas_funcionario3 * 0.15
    print("Funcionario 03 recebeu {} em bonus".format(bonus))
elif (vendas_funcionario3 < (meta * 2)) and (vendas_funcionario3 >= meta):
    bonus = vendas_funcionario3 * 0.10
    print("Funcionário 03 recebeu {} em bonus".format(bonus))
else:
    print("O funcionário 03 ganhou 0 bonus")

"""Resposta:
O funcionário 1 ganhou 100 de bônus
O funcionário 2 ganhou 0 de bônus
O funcionário 3 ganhou 405 de bônus
"""