# -*- coding: utf-8 -*-
"""
Exercícios Módulo 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fPXuUS-NeoH8ABii8q2EKRU5LPdlGuA

# Exercícios do Módulo 1 - Operações, Variáveis e Input

### Parte 1 - Operações e Variáveis
Crie um programa que imprima (print) os principais indicadores da loja Hashtag&Drink no último ano.
Obs: faça tudo usando variáveis.

Valores do último ano:

Quantidade de Vendas de Coca = 150
Quantidade de Vendas de Pepsi = 130
Preço Unitário da Coca = 1,50
Preço Unitário da Pepsi = 1,50
Custo da Loja: 2.500,00

Use o bloco abaixo para criar todas as variáveis que precisar.
"""

coca_vendas = 150
pepsi_vendas = 150
coca_custo = 1.50
pepsi_custo = 1.50
loja_custo = 2500
faturamento_pepsi = pepsi_vendas * pepsi_custo
faturamento_coca = coca_vendas * coca_custo
lucro_loja = (faturamento_coca + faturamento_pepsi) - loja_custo
margem_loja = lucro_loja / (faturamento_coca + faturamento_pepsi)

"""1. Qual foi o faturamento de Pepsi da Loja?"""
print("Faturamento de Pepsi: " + str(faturamento_pepsi))

"""2. Qual foi o faturamento de Coca da Loja?"""
print("Faturamento de Coca: " + str(faturamento_coca))

"""3. Qual foi o Lucro da loja?"""
print("Lucro da Loja: " + str(lucro_loja))

"""4. Qual foi a Margem da Loja? (Lembre-se, margem = Lucro / Faturamento). Não precisa formatar em percentual"""
print("A margem de lucro da loja é: " + str(margem_loja))

"""
### Parte 2 - Inputs e Strings

A maioria das empresas trabalham com um Código para cada produto que possuem.
A Hashtag&Drink, por exemplo, tem mais de 1.000 produtos e possui um código para cada produto.

Ex: 
Coca -> Código: BEB1300543<br>
Pepsi -> Código: BEB1300545<br>
Vinho Primitivo Lucarelli -> Código: BAC1546001<br>
Vodka Smirnoff -> Código: BAC17675002<br>

Todas as bebidas não alcóolicas tem o início do Código "BEB" e todas as bebidas alcóolicas tem o início do código "BAC".

Crie um programa de consulta que, dado um código qualquer, identifique se a bebida é alcóolica.
True para bebidas alcóolicas;
False para bebidas não alcóolicas.
Para inserir um código, use um input.

Dica: Lembre-se do setaduser in para strings e sempre insira os códigos com letra maiúscula para facilitar.
"""

coca = "BEB1300543"
pepsi = "BEB1300545"
vinho_lucarelli = "BAC1546001"
vodka_smirnoff = "BAC17675002"

consulta = input("Digite o Código da Bebida e diremos se é alcóolica: ")
print("BAC" in str(consulta))
