# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]
vendas_ano = vendas_1sem + vendas_2sem

vendas_max = vendas_ano.index(max(vendas_ano))
vendas_min = vendas_ano.index(min(vendas_ano))

"""
## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""

faturamento = sum(vendas_ano)
melhor_mes = max(vendas_ano) / faturamento

print("O mês com maior vendas foi {}, com um total de {} vendas".format(meses[vendas_max], vendas_ano[vendas_max]))
print("O mês com pior vendas foi {}, com um total de {} vendas".format(meses[vendas_min], vendas_ano[vendas_min]))
print()
print("O faturamento do ano foi de R${:,.2f}.\nO mês de {} representou {:.2%} do faturamento"
      .format(faturamento,
              meses[vendas_max],
              melhor_mes))
print()

"""
## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""
top3 = []

vendas_ano.sort(reverse=True)
top3.append(vendas_ano[0])
top3.append(vendas_ano[1])
top3.append(vendas_ano[2])
print(top3)
